import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import LoadingIcons from "react-loading-icons";
import Footer from "../../components/footer";
import Header from "../../components/header";
import { trpc } from "../../utils/trpc";

const SubCategories = () => {
  const router = useRouter();
  const id = Array.isArray(router.query.id)
    ? router.query.id[0]
    : router.query.id;

  console.log("id:" + id);

  // Hack, sille jos id onkin undefined - miten tän tekisi paremmin?
  // Pitäisikö laittaa, että id voi olla nullish routerissa?
  const { data, isLoading } = trpc.subCategory.getById.useQuery({
    id: id ? id : "xx",
  });

  return (
    <div className="flex h-full flex-col px-8">
      <Head>
        <title>Digiapua lukiolaiselle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="main-color container mx-auto grid flex-1 grid-cols-1 gap-x-8 gap-y-2 overflow-y-scroll text-2xl md:grid-cols-2 lg:grid-cols-3">
        {isLoading ? (
          <LoadingIcons.Circles className="max-h-9" />
        ) : (
          data?.map((subcat) => (
            <div key={subcat.id} className="flex items-center justify-center">
              <Link href={`/videos/${subcat.id}`}>
                <a className="hover:main-color-hover flex h-40 w-60 items-center justify-center rounded-2xl border-2 border-solid py-9 px-2 text-center">
                  <p>{subcat.name}</p>
                </a>
              </Link>
            </div>
          ))
        )}
      </div>
      <Footer />
    </div>
  );
};

export default SubCategories;
